<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Apricot 1.3</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <style type="text/css">
    body {
        overflow:hidden!important;
        padding-top: 120px;
    }
    #con{
        margin-top: 10px;
        color: black;
    }
    </style>
    <!-- Le styles -->
    <script type="text/javascript" src="{{ asset('assets/js/jquery.min.js') }}"></script>

    <link rel="stylesheet" href="{{ asset('assets/css/style.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/loader-style.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/bootstrap.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/signin.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/extra-pages.css') }}">

    <link rel="shortcut icon" href="{{ asset('assets/ico/minus.png') }}">
</head>

<body id="lock">
    <!-- Preloader -->
    <div id="preloader">
        <div id="status">&nbsp;</div>
    </div>




    <!-- Main content -->
    <section class="page-error">

        <div class="headline-lock text-center" id="time">
            <span></span>
            <!-- Time auto generated by js -->
        </div>
        <!-- /.headline -->
        <div class="lockscreen-name">{{ session('master')->name }}</div>
        <div class="lockscreen-image">
            <img src="/admin-uploads/{{ session('master')->img }}" alt="user image">
        </div>


                    <!-- User name -->
            @if (count($errors) > 0)
                        <div class="lockscreen-item">
                         <ul id = "con">
                             @foreach ($errors->all() as $error)&nbsp;&nbsp;
                             {{ $error }}
                             @endforeach
                         </ul>
                      </div>
            @endif
                                
             <!-- 错误提示信息 -->
             @if (session('info.error'))                 
                   <div class="lockscreen-item">
                         <ul id = "con">
                         {{ session('info.error') }}
                         </ul>
                    </div>
              @endif
            <!-- 错误提示信息 -->

        <!-- START LOCK SCREEN ITEM -->
        <div class="lockscreen-item">


            <!-- lockscreen credentials (contains the form) -->
            <div class="lockscreen-credentials">
                <form action="{{ url('/admin/rewait') }}" method="post">
                    {{ csrf_field() }}
                <div class="input-group">
                    <input type="password" class="form-control" placeholder="请输入密码" name="password">
                    <div class="input-group-btn">
                        <button class="btn btn-flat"><i class="fa fa-arrow-right text-muted"></i>
                        </button>
                    </div>
                </div>
                </form>
            </div>
            <!-- /.lockscreen credentials -->

        </div>
        <!-- /.lockscreen-item -->

        <div class="lockscreen-link">
            <a class="lock-link" href="{{ url('/admin/login') }}">或者作为一个不同的用户登录</a>
        </div>

    </section>

    <!--  END OF PAPER WRAP -->

    <script type="text/javascript" src="{{ url('assets/js/load.js') }}"></script>
    <script type="text/javascript" src="{{ url('assets/js/main.js') }}"></script>
    <script type="text/javascript">
    $(function() {
        startTime();
        $(".center").center();
        $(window).resize(function() {
            $(".center").center();
        });
    });

    /*  */

    function startTime() {
        var today = new Date();
        var h = today.getHours();
        var m = today.getMinutes();
        var s = today.getSeconds();

        // add a zero in front of numbers<10
        m = checkTime(m);
        s = checkTime(s);

        //Check for PM and AM
        var day_or_night = (h > 11) ? "PM" : "AM";

        //Convert to 12 hours system
        if (h > 12)
            h -= 12;

        //Add time to the headline and update every 500 milliseconds
        $('#time').html(h + ":" + m + ":" + s + " " + day_or_night);
        setTimeout(function() {
            startTime()
        }, 500);
    }

    function checkTime(i) {
        if (i < 10) {
            i = "0" + i;
        }
        return i;
    }

    /* CENTER ELEMENTS IN THE SCREEN */
    jQuery.fn.center = function() {
        this.css("position", "absolute");
        this.css("top", Math.max(0, (($(window).height() - $(this).outerHeight()) / 2) +
            $(window).scrollTop()) - 30 + "px");
        this.css("left", Math.max(0, (($(window).width() - $(this).outerWidth()) / 2) +
            $(window).scrollLeft()) + "px");
        return this;
    }
    $("#con").fadeOut(5000);
    </script>


</body>

</html>
